---
dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/tests/static/collections-requirements.yml
driver:
  name: default
platforms:
  - name: zt-zerotouch-molecule-lockdown
provisioner:
  name: ansible
  inventory:
    host_vars:
      zt-zerotouch-molecule-lockdown:
        ansible_connection: local
scenario:
  test_sequence:
    - dependency
    - create
    - converge
    - verify
    - destroy
verifier:
  name: ansible
