---
name: Static Checks

"on":
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:
    branches:
    - main

jobs:
  static-checks:
    name: Run yamllint and ansible-lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.12'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run static checks
      run: |
        pip install tox
        tox -c tests/static
